### PR TITLE
Adds deeper introduction to label configuration in quickstart.md

### PR DESCRIPTION
**Pull request by adunmore**
The current introduction to label configuration in quickstart.md misses some important details.

This adds a deeper introduction to the purpose and requirements of the labels query. It also provides more context for the given example query.

### CODE REVIEW

**Comment by adunmore** [comment]
Possible that this explanation is too verbose for the quickstart guide? I'm open to adapting it to another place in the docs.

**Comment by thcrock** [comment]
Is the level of detail about labels in in https://dssg.github.io/triage/experiments/cohort-labels/ too much? Is there some happy medium between that and what's in the quickstart right now?

**Comment by thcrock** [comment]
My apologies: when this came up on my feed I thought it was an issue, not a pull request with something already written. This does seem like a happy medium between the old quickstart and the deep dive.

**Comment by shaycrk** [comment]
Yeah, this looks good to me, too -- I think the example query will be helpful, but is still short enough for the quickstart.

**Pull request merged**
