### PR TITLE
Reliability curve Solves #179

### PR DESCRIPTION
**Pull request by avishekrk**
Adds reliability curve to the Model Evaluator

### CODE REVIEW

**Comment by avishekrk** [comment]
Here is the output of the function: https://gist.github.com/avishekrk/26c41ed27f7cc81974833eba61ecd1e3

**Comment by nanounanue** [comment]
We should move this code to the branch `post-postmodeling` ...

**Comment by nanounanue** [comment]
Also, What is the difference between this and the "deconstructed ROC curve" in the original postmodeling?

**Comment by avishekrk** [comment]
> Also, What is the difference between this and the "deconstructed ROC curve" in the original postmodeling?

I don't know what a "deconstructed ROC curve" actually it. But looking at the code that is  not dong any score calibration. The reliability curve is comparing model scores to empirical probabilities to see how reliable they are as empirical probabilities.

**Comment by avishekrk** [comment]
> We should move this code to the branch `post-postmodeling` ...

Sure that is fine.

**Comment by avishekrk** [comment]
Closing this branch and PR. Moved Feature to `post-postmodeling`

**Pull request closed without merging**
