### PR TITLE
Closes #715

### LINKED ISSUE #715: I cannot run the tutorial.sh
I was super excited that I finally got time to run triage.

Buuut, I couldn't get to the second step of the tutorial.

In the step

`./tutorial.sh start`

I got a `ERROR: Couldn't find env file: /Users/joaoc/Documents/Projects/triage/docs/sources/dirtyduck/.env` as an answer.

Did I miss something? I checked the directory but there is no `.env` file.

I am using a Mac.

### PR DESCRIPTION
**Pull request by nanounanue**
Missing library `bzip2` added

### CODE REVIEW

**Comment by shaycrk** [comment]
Hmmm @nanounanue, mind looking at what's going on with the failed checks?

**Comment by thcrock** [comment]
I noticed a matplotlib version problem for Travis. Matplotlib may need to be pinned at an earlier version

**Comment by thcrock** [comment]
On second look, I think the Travis failures are related to #734

**Comment by nanounanue** [comment]
> On second look, I think the Travis failures are related to #734

I just fixed that

**Comment by nanounanue** [comment]
Ok, let me check. It failed again.

**Comment by nanounanue** [comment]
The error in Travis CI was solved in #747 , this **PR** is safe to be merged into `master`

**Comment by shaycrk** [comment]
sounds good -- I just merged #747 so will go ahead and pull this in as well.

**Pull request merged**
