### PR TITLE
Fixing naming

### LINKED ISSUE #396: results.model_groups should reference "hyperparameters" rather than "parameters"
`results.model_groups` has a `model_parameters` column, which refers to hyperparameters (e.g. L2 penalty for logistic regression) rather than parameters (e.g. coefficient for a particular feature in logistic regression). We should rename the column for clarity.

### LINKED ISSUE #404: The column `n_examples` should be renamed to observations
In the table `model_metadata.matrices` the column `n_examples` should be renamed to `observations`, `num_observations`, `num_rows`, `rows`, `num_samples`, `samples` (pick one)

### LINKED ISSUE #405: In the schemas `test_results` and `train_results` the prefix `test` and `train`  in the tables is redundant
Change 

`test_results.test_evaluations` -> `test_results.evaluations` 

for example

### LINKED ISSUE #407: Unify sintax in scoring section in the configuration file
Currently is:

```
scoring:
    sort_seed: 5
    metric_groups:
        -
          metrics: [precision@, recall@]
          thresholds:
            percentiles: [5.0, 10.0]
            top_n: [5, 10, 25]

    training_metric_groups:
      -
        metrics: [accuracy]
      -
        metrics: [precision@, recall@]
        thresholds:
          percentiles: [5.0, 10.0]
          top_n: [5, 10, 25]
```

It should be better to rename the first `metric_groups` to `testing_metric_groups` for consistency, i.e.

```
scoring:
    sort_seed: 5
    testing_metric_groups:
        -
          metrics: [precision@, recall@]
          thresholds:
            percentiles: [5.0, 10.0]
            top_n: [5, 10, 25]

    training_metric_groups:
      -
        metrics: [accuracy]
      -
        metrics: [precision@, recall@]
        thresholds:
          percentiles: [5.0, 10.0]
          top_n: [5, 10, 25]
```

### PR DESCRIPTION
**Pull request by nanounanue**
Closes #396 
Closes #404 
Closes #407 
Closes #405

### CODE REVIEW

**Comment by thcrock** [comment]
Running the build in Travis had some problems. From skimming the errors, I see that the model group stored procedure needs to be changed as well: https://github.com/dssg/triage/blob/master/src/triage/component/catwalk/model_group_stored_procedure.sql

**Comment by nanounanue** [comment]
You are right. I will fix those. Just curious, What is the purpose of those store procedures?

**Comment by thcrock** [comment]
I steered you slightly the wrong way. The build still failed ( https://travis-ci.org/dssg/triage/builds/387879125 ) It looks like the copy of model_group_stored_procedure.sql in catwalk is not used, likely got caught up in merge madness.  The real one is in the results schema. You can remove the file in catwalk.

**Comment by nanounanue** [comment]
I will do :)

**Pull request merged**
